import { FlyerTemplateConfig, FlyerData } from './types';

export const PRESET_TEMPLATES: FlyerTemplateConfig[] = [
  /* ============================== FREE ============================== */
  {
    id: 'elegante-minimal-template',
    name: 'Elegante Minimalista',
    plan: 'FREE',
    category: 'PARTICIPACAO',
    description: 'Linhas limpas, tipografia generosa e uma única moldura fina. Design HD discreto e moderno.',
    primaryColor: '#0f172a',
    secondaryColor: '#ffffff',
    accentColor: '#94a3b8',
    fontFamily: 'sans',
    layoutStyle: 'elegante-minimal',
  },
  {
    id: 'classico-sobrio-template',
    name: 'Clássico Sóbrio',
    plan: 'FREE',
    category: 'PARTICIPACAO',
    description: 'Preto e branco com serifa clássica, cruz ornamentada e moldura dupla. Respeito e tradição.',
    primaryColor: '#1c1917',
    secondaryColor: '#fafaf9',
    accentColor: '#a8a29e',
    fontFamily: 'serif',
    layoutStyle: 'classico-sobrio',
  },
  {
    id: 'floral-suave-template',
    name: 'Floral Suave',
    plan: 'FREE',
    category: 'PARTICIPACAO',
    description: 'Ramo de flores suaves em tons pastel, evocando serenidade e carinho.',
    primaryColor: '#44403c',
    secondaryColor: '#fdfbf7',
    accentColor: '#d6b8a0',
    fontFamily: 'serif',
    layoutStyle: 'floral-suave',
  },

  /* ============================== PREMIUM ============================== */
  {
    id: 'dourado-premium-template',
    name: 'Dourado Imperial',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Relevo dourado, cantoneiras ornamentadas e véu de brilho. Dignidade máxima para a despedida.',
    primaryColor: '#111827',
    secondaryColor: '#fffdf5',
    accentColor: '#c9a227',
    fontFamily: 'serif',
    layoutStyle: 'dourado-premium',
  },
  {
    id: 'marmore-premium-template',
    name: 'Textura Mármore',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Fundo de mármore nobre com veios subtis e medalhão de foto em relevo.',
    primaryColor: '#292524',
    secondaryColor: '#f5f1ea',
    accentColor: '#b99b6b',
    fontFamily: 'serif',
    layoutStyle: 'marmore-premium',
  },
  {
    id: 'luz-radiante-template',
    name: 'Luz Radiante',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Raios de luz celestial emanando do topo, sobre fundo azul-noite profundo. Esperança e elevação.',
    primaryColor: '#0b1120',
    secondaryColor: '#0e1a2f',
    accentColor: '#e8c96a',
    fontFamily: 'sans',
    layoutStyle: 'luz-radiante',
  },
  {
    id: 'jardim-premium-template',
    name: 'Jardim da Saudade',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Alecrim, oliveira e rosas desenhadas à mão numa moldura de jardim em tons verdes e creme.',
    primaryColor: '#1c2b21',
    secondaryColor: '#f7f5ee',
    accentColor: '#7d9b76',
    fontFamily: 'serif',
    layoutStyle: 'jardim-premium',
  },
  {
    id: 'velas-premium-template',
    name: 'Chama de Velas',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Velas acesas em silhueta, aurora quente e espaço para uma mensagem de despedida.',
    primaryColor: '#191208',
    secondaryColor: '#2b1f10',
    accentColor: '#e0a458',
    fontFamily: 'serif',
    layoutStyle: 'velas-premium',
  },

  /* ============================== ULTRA ============================== */
  {
    id: 'profundidade-3d-template',
    name: 'Profundidade 3D',
    plan: 'ULTRA',
    category: 'PARTICIPACAO',
    description: 'Camadas com perspetiva, sombras profundas e movimento parallax subtil no ecrã.',
    primaryColor: '#0c0a1d',
    secondaryColor: '#1a1435',
    accentColor: '#c7b9ff',
    fontFamily: 'display',
    layoutStyle: 'profundidade-3d',
    animated: true,
  },
  {
    id: 'aquarela-ultra-template',
    name: 'Aquarela Celeste',
    plan: 'ULTRA',
    category: 'PARTICIPACAO',
    description: 'Efeito de aquarela com lavagens de cor desenhadas em CSS e manchas suaves de tinta.',
    primaryColor: '#334155',
    secondaryColor: '#f8fafc',
    accentColor: '#7aa2c4',
    fontFamily: 'serif',
    layoutStyle: 'aquarela-ultra',
    animated: true,
  },
  {
    id: 'video-ultra-template',
    name: 'Céu em Movimento',
    plan: 'ULTRA',
    category: 'PARTICIPACAO',
    description: 'Fundo de vídeo em silêncio (estrelas, nuvens ou chama) com sobreposição elegante. Compatível com partilha digital.',
    primaryColor: '#020617',
    secondaryColor: '#0b1220',
    accentColor: '#fcd34d',
    fontFamily: 'sans',
    layoutStyle: 'video-ultra',
    animated: true,
  },

  /* ============================== NOVOS PROFISSIONAIS ============================== */
  {
    id: 'cruz-dourada-template',
    name: 'Cruz Dourada',
    plan: 'FREE',
    category: 'PARTICIPACAO',
    description: 'Fundo azul profundo com cruz dourada luminosa, moldura em arco e cartão de informações elegante.',
    primaryColor: '#0f1a2e',
    secondaryColor: '#ffffff',
    accentColor: '#d4af37',
    fontFamily: 'sans',
    layoutStyle: 'cruz-dourada',
  },
  {
    id: 'memoria-viva-template',
    name: 'Memória Viva',
    plan: 'FREE',
    category: 'PARTICIPACAO',
    description: 'Layout dividido moderno com foto em grande formato e painel de informação limpo e organizado.',
    primaryColor: '#111827',
    secondaryColor: '#ffffff',
    accentColor: '#b08d57',
    fontFamily: 'sans',
    layoutStyle: 'memoria-viva',
  },
  {
    id: 'rosa-eterna-template',
    name: 'Rosa Eterna',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Tons rosados suaves com moldura dupla, rosas ornamentais nos cantos e foto em arco romântico.',
    primaryColor: '#4a2c3a',
    secondaryColor: '#fdf6f4',
    accentColor: '#c48b9f',
    fontFamily: 'serif',
    layoutStyle: 'rosa-eterna',
  },
  {
    id: 'pomba-paz-template',
    name: 'Pomba da Paz',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Pomba branca em voo sobre céu suave, foto circular em medalhão e cartões de informação flutuantes.',
    primaryColor: '#1e293b',
    secondaryColor: '#f7fafc',
    accentColor: '#8fa8bf',
    fontFamily: 'serif',
    layoutStyle: 'pomba-paz',
  },
  {
    id: 'horizonte-sereno-template',
    name: 'Horizonte Sereno',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Gradiente do crepúsculo ao amanhecer — do azul noite ao dourado suave. Renascimento e esperança.',
    primaryColor: '#1b2440',
    secondaryColor: '#fdf6ea',
    accentColor: '#e8a75d',
    fontFamily: 'sans',
    layoutStyle: 'horizonte-sereno',
  },
  {
    id: 'noite-estrelada-template',
    name: 'Noite Estrelada',
    plan: 'ULTRA',
    category: 'PARTICIPACAO',
    description: 'Céu noturno com estrelas cintilantes animadas, título em degradê dourado e brilho etéreo na foto.',
    primaryColor: '#050816',
    secondaryColor: '#0b1230',
    accentColor: '#fcd34d',
    fontFamily: 'display',
    layoutStyle: 'noite-estrelada',
    animated: true,
  },
  {
    id: 'folhas-outono-template',
    name: 'Folhas de Outono',
    plan: 'FREE',
    category: 'PARTICIPACAO',
    description: 'Folhas outonais em tons quentes que flutuam suavemente. Acolhedor, sereno e natural.',
    primaryColor: '#3d2f23',
    secondaryColor: '#faf6ef',
    accentColor: '#b5722e',
    fontFamily: 'serif',
    layoutStyle: 'folhas-outono',
  },
  {
    id: 'anjo-guardiao-template',
    name: 'Anjo Guardião',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Asas de anjo em dourado suave a abraçar a foto, com luz celestial no topo. Proteção e fé.',
    primaryColor: '#4a3b28',
    secondaryColor: '#fbf7ee',
    accentColor: '#c9a86a',
    fontFamily: 'serif',
    layoutStyle: 'anjo-guardiao',
  },
  {
    id: 'pergaminho-classico-template',
    name: 'Pergaminho Clássico',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Estilo vintage em papel envelhecido com cantos ornamentados e texto à maneira antiga.',
    primaryColor: '#332414',
    secondaryColor: '#f2e8d5',
    accentColor: '#8a6d46',
    fontFamily: 'serif',
    layoutStyle: 'pergaminho-classico',
  },
  {
    id: 'cristal-azul-template',
    name: 'Cristal Azul',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Glassmorphism moderno sobre azul profundo — painéis translúcidos, foto circular com halo.',
    primaryColor: '#0a1628',
    secondaryColor: '#10233f',
    accentColor: '#7fb2d9',
    fontFamily: 'sans',
    layoutStyle: 'cristal-azul',
  },
  {
    id: 'luz-eterna-template',
    name: 'Luz Eterna',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Brasa dourada que irradia da base como uma vela infinita. Calor, memória e eternidade.',
    primaryColor: '#120b04',
    secondaryColor: '#1a1208',
    accentColor: '#f0c46a',
    fontFamily: 'serif',
    layoutStyle: 'luz-eterna',
  },
  {
    id: 'aurora-boreal-template',
    name: 'Aurora Boreal',
    plan: 'ULTRA',
    category: 'PARTICIPACAO',
    description: 'Aurora animada em verde-esmeralda e violeta sobre céu noturno, com título em degradê luminoso.',
    primaryColor: '#04101e',
    secondaryColor: '#062033',
    accentColor: '#5eead4',
    fontFamily: 'display',
    layoutStyle: 'aurora-boreal',
    animated: true,
  },
  {
    id: 'ondas-serenidade-template',
    name: 'Ondas de Serenidade',
    plan: 'ULTRA',
    category: 'PARTICIPACAO',
    description: 'Ondas suaves animadas em tons turquesa que evocam calma, paz e eterno fluir.',
    primaryColor: '#134e4a',
    secondaryColor: '#f3faf9',
    accentColor: '#35b8a8',
    fontFamily: 'sans',
    layoutStyle: 'ondas-serenidade',
    animated: true,
  },

  /* ============================== LEGADOS (mantidos) ============================== */
  {
    id: 'casa-hortas-template',
    name: 'Modelo Casa Hortas (Azul & Dourado)',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Design premium baseado no modelo tradicional com cabeçalho azul escuro, moldura em arco dourado para foto, ícones elegantes e cartão da agência com brasão.',
    primaryColor: '#0a192f',
    secondaryColor: '#ffffff',
    accentColor: '#d4af37',
    fontFamily: 'sans',
    layoutStyle: 'casa-hortas',
  },
  {
    id: 'classico-ouro-template',
    name: 'Modelo Clássico Dourado',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Estilo sóbrio e solene com moldura dourada ornamentada e tipografia serifa luxuosa.',
    primaryColor: '#0f172a',
    secondaryColor: '#f8fafc',
    accentColor: '#c5a059',
    fontFamily: 'serif',
    layoutStyle: 'classico-ouro',
  },
  {
    id: 'sereno-minimal-template',
    name: 'Modelo Sereno Minimalista',
    plan: 'FREE',
    category: 'PARTICIPACAO',
    description: 'Visual moderno e limpo, ideal para leitura rápida e impressão económica.',
    primaryColor: '#1e293b',
    secondaryColor: '#ffffff',
    accentColor: '#64748b',
    fontFamily: 'sans',
    layoutStyle: 'sereno-minimal',
  },
];

export const FREE_TEMPLATES = PRESET_TEMPLATES.filter((t) => t.plan === 'FREE');
export const PREMIUM_TEMPLATES = PRESET_TEMPLATES.filter((t) => t.plan === 'PREMIUM');
export const ULTRA_TEMPLATES = PRESET_TEMPLATES.filter((t) => t.plan === 'ULTRA');

export const PLAN_LABELS: Record<'FREE' | 'PREMIUM' | 'ULTRA', string> = {
  FREE: 'Free',
  PREMIUM: 'Premium',
  ULTRA: 'Ultra',
};

export const DEFAULT_FLYER_DATA: FlyerData = {
  title: 'PARTICIPAÇÃO DE FALECIMENTO',
  deceasedName: 'LUÍS FILIPE DA SILVA FREITAS',
  age: 27,
  photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800',
  funeralDate: '2026-07-08',
  funeralTime: '17:00',
  funeralDateFormatted: 'Quarta-feira, dia 8 de julho, 17:00 horas',
  parishLocation: 'Igreja Paroquial da Ventosa, Braga',
  cemeteryLocation: 'Ventosa, Vieira do Minho',
  deathLocation: 'Hospital de Braga',
  wakeDate: '2026-07-08',
  wakeTime: '15:30',
  wakeLocation: 'Igreja Paroquial da Ventosa',
  wakeDetailsFormatted: 'Quarta-feira, dia 8 de julho, 15:30 horas, na Igreja Paroquial da Ventosa',
  agencyName: 'Funerária Casa Hortas, Lda',
  agencyAddress: 'Rua das Maceirinhas, Cabreiros, Braga',
  agencyLocation: 'Ventosa, Vieira do Minho',
  agencyFounded: 'DESDE 1890',
  agencyWebsite: 'www.casahortas.com',
  agencyLogoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=300',
  agencyLogoType: 'INITIALS',
  agencyInitials: 'CH',
  primaryColor: '#0a192f',
  accentColor: '#d4af37',
  fontFamily: 'sans',
};
