import { FlyerTemplateConfig, FlyerData } from './types';

export const PRESET_TEMPLATES: FlyerTemplateConfig[] = [
  /* ============================== FREE ============================== */
  {
    id: 'elegante-minimal-template',
    name: 'Elegante Minimalista',
    plan: 'FREE',
    category: 'PARTICIPACAO',
    description: 'Linhas limpas, tipografia generosa e uma única moldura fina. Design HD discreto e moderno.',
    primaryColor: '#0f172a',
    secondaryColor: '#ffffff',
    accentColor: '#94a3b8',
    fontFamily: 'sans',
    layoutStyle: 'elegante-minimal',
  },
  {
    id: 'classico-sobrio-template',
    name: 'Clássico Sóbrio',
    plan: 'FREE',
    category: 'PARTICIPACAO',
    description: 'Preto e branco com serifa clássica, cruz ornamentada e moldura dupla. Respeito e tradição.',
    primaryColor: '#1c1917',
    secondaryColor: '#fafaf9',
    accentColor: '#a8a29e',
    fontFamily: 'serif',
    layoutStyle: 'classico-sobrio',
  },
  {
    id: 'floral-suave-template',
    name: 'Floral Suave',
    plan: 'FREE',
    category: 'PARTICIPACAO',
    description: 'Ramo de flores suaves em tons pastel, evocando serenidade e carinho.',
    primaryColor: '#44403c',
    secondaryColor: '#fdfbf7',
    accentColor: '#d6b8a0',
    fontFamily: 'serif',
    layoutStyle: 'floral-suave',
  },

  /* ============================== PREMIUM ============================== */
  {
    id: 'dourado-premium-template',
    name: 'Dourado Imperial',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Relevo dourado, cantoneiras ornamentadas e véu de brilho. Dignidade máxima para a despedida.',
    primaryColor: '#111827',
    secondaryColor: '#fffdf5',
    accentColor: '#c9a227',
    fontFamily: 'serif',
    layoutStyle: 'dourado-premium',
  },
  {
    id: 'marmore-premium-template',
    name: 'Textura Mármore',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Fundo de mármore nobre com veios subtis e medalhão de foto em relevo.',
    primaryColor: '#292524',
    secondaryColor: '#f5f1ea',
    accentColor: '#b99b6b',
    fontFamily: 'serif',
    layoutStyle: 'marmore-premium',
  },
  {
    id: 'luz-radiante-template',
    name: 'Luz Radiante',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Raios de luz celestial emanando do topo, sobre fundo azul-noite profundo. Esperança e elevação.',
    primaryColor: '#0b1120',
    secondaryColor: '#0e1a2f',
    accentColor: '#e8c96a',
    fontFamily: 'sans',
    layoutStyle: 'luz-radiante',
  },
  {
    id: 'jardim-premium-template',
    name: 'Jardim da Saudade',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Alecrim, oliveira e rosas desenhadas à mão numa moldura de jardim em tons verdes e creme.',
    primaryColor: '#1c2b21',
    secondaryColor: '#f7f5ee',
    accentColor: '#7d9b76',
    fontFamily: 'serif',
    layoutStyle: 'jardim-premium',
  },
  {
    id: 'velas-premium-template',
    name: 'Chama de Velas',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Velas acesas em silhueta, aurora quente e espaço para uma mensagem de despedida.',
    primaryColor: '#191208',
    secondaryColor: '#2b1f10',
    accentColor: '#e0a458',
    fontFamily: 'serif',
    layoutStyle: 'velas-premium',
  },

  /* ============================== ULTRA ============================== */
  {
    id: 'profundidade-3d-template',
    name: 'Profundidade 3D',
    plan: 'ULTRA',
    category: 'PARTICIPACAO',
    description: 'Camadas com perspetiva, sombras profundas e movimento parallax subtil no ecrã.',
    primaryColor: '#0c0a1d',
    secondaryColor: '#1a1435',
    accentColor: '#c7b9ff',
    fontFamily: 'display',
    layoutStyle: 'profundidade-3d',
    animated: true,
  },
  {
    id: 'aquarela-ultra-template',
    name: 'Aquarela Celeste',
    plan: 'ULTRA',
    category: 'PARTICIPACAO',
    description: 'Efeito de aquarela com lavagens de cor desenhadas em CSS e manchas suaves de tinta.',
    primaryColor: '#334155',
    secondaryColor: '#f8fafc',
    accentColor: '#7aa2c4',
    fontFamily: 'serif',
    layoutStyle: 'aquarela-ultra',
    animated: true,
  },
  {
    id: 'video-ultra-template',
    name: 'Céu em Movimento',
    plan: 'ULTRA',
    category: 'PARTICIPACAO',
    description: 'Fundo de vídeo em silêncio (estrelas, nuvens ou chama) com sobreposição elegante. Compatível com partilha digital.',
    primaryColor: '#020617',
    secondaryColor: '#0b1220',
    accentColor: '#fcd34d',
    fontFamily: 'sans',
    layoutStyle: 'video-ultra',
    animated: true,
  },

  /* ============================== LEGADOS (mantidos) ============================== */
  {
    id: 'casa-hortas-template',
    name: 'Modelo Casa Hortas (Azul & Dourado)',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Design premium baseado no modelo tradicional com cabeçalho azul escuro, moldura em arco dourado para foto, ícones elegantes e cartão da agência com brasão.',
    primaryColor: '#0a192f',
    secondaryColor: '#ffffff',
    accentColor: '#d4af37',
    fontFamily: 'sans',
    layoutStyle: 'casa-hortas',
  },
  {
    id: 'classico-ouro-template',
    name: 'Modelo Clássico Dourado',
    plan: 'PREMIUM',
    category: 'PARTICIPACAO',
    description: 'Estilo sóbrio e solene com moldura dourada ornamentada e tipografia serifa luxuosa.',
    primaryColor: '#0f172a',
    secondaryColor: '#f8fafc',
    accentColor: '#c5a059',
    fontFamily: 'serif',
    layoutStyle: 'classico-ouro',
  },
  {
    id: 'sereno-minimal-template',
    name: 'Modelo Sereno Minimalista',
    plan: 'FREE',
    category: 'PARTICIPACAO',
    description: 'Visual moderno e limpo, ideal para leitura rápida e impressão económica.',
    primaryColor: '#1e293b',
    secondaryColor: '#ffffff',
    accentColor: '#64748b',
    fontFamily: 'sans',
    layoutStyle: 'sereno-minimal',
  },
];

export const FREE_TEMPLATES = PRESET_TEMPLATES.filter((t) => t.plan === 'FREE');
export const PREMIUM_TEMPLATES = PRESET_TEMPLATES.filter((t) => t.plan === 'PREMIUM');
export const ULTRA_TEMPLATES = PRESET_TEMPLATES.filter((t) => t.plan === 'ULTRA');

export const PLAN_LABELS: Record<'FREE' | 'PREMIUM' | 'ULTRA', string> = {
  FREE: 'Free',
  PREMIUM: 'Premium',
  ULTRA: 'Ultra',
};

export const DEFAULT_FLYER_DATA: FlyerData = {
  title: 'PARTICIPAÇÃO DE FALECIMENTO',
  deceasedName: 'LUÍS FILIPE DA SILVA FREITAS',
  age: 27,
  photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800',
  funeralDate: '2026-07-08',
  funeralTime: '17:00',
  funeralDateFormatted: 'Quarta-feira, dia 8 de julho, 17:00 horas',
  parishLocation: 'Igreja Paroquial da Ventosa, Braga',
  cemeteryLocation: 'Ventosa, Vieira do Minho',
  deathLocation: 'Hospital de Braga',
  wakeDate: '2026-07-08',
  wakeTime: '15:30',
  wakeLocation: 'Igreja Paroquial da Ventosa',
  wakeDetailsFormatted: 'Quarta-feira, dia 8 de julho, 15:30 horas, na Igreja Paroquial da Ventosa',
  agencyName: 'Funerária Casa Hortas, Lda',
  agencyAddress: 'Rua das Maceirinhas, Cabreiros, Braga',
  agencyLocation: 'Ventosa, Vieira do Minho',
  agencyFounded: 'DESDE 1890',
  agencyWebsite: 'www.casahortas.com',
  agencyLogoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=300',
  agencyLogoType: 'INITIALS',
  agencyInitials: 'CH',
  primaryColor: '#0a192f',
  accentColor: '#d4af37',
  fontFamily: 'sans',
};
