import type { FlyerData } from '@/lib/types';

export const LAYOUT_FIXTURE: FlyerData = {
  title: 'PARTICIPAÇÃO DE FALECIMENTO',
  deceasedName: 'LUÍS FILIPE DA SILVA FREITAS',
  age: 27,
  photoUrl: 'https://images.example.com/deceased.jpg',
  funeralDate: '2026-07-08',
  funeralTime: '17:00',
  funeralDateFormatted: 'Quarta-feira, dia 8 de julho, 17:00 horas',
  parishLocation: 'Igreja Paroquial da Ventosa, Braga',
  cemeteryLocation: 'Ventosa, Vieira do Minho',
  deathLocation: 'Hospital de Braga',
  wakeDate: '2026-07-08',
  wakeTime: '15:30',
  wakeLocation: 'Igreja Paroquial da Ventosa',
  wakeDetailsFormatted: 'Quarta-feira, dia 8 de julho, 15:30 horas',
  agencyName: 'Funerária Casa Hortas, Lda',
  agencyAddress: 'Rua das Maceirinhas, Cabreiros, Braga',
  agencyLocation: 'Ventosa, Vieira do Minho',
  agencyFounded: 'DESDE 1890',
  agencyWebsite: 'www.casahortas.com',
  agencyLogoUrl: 'https://images.example.com/logo.png',
  agencyLogoType: 'INITIALS',
  agencyInitials: 'CH',
  primaryColor: '#0a192f',
  accentColor: '#d4af37',
  fontFamily: 'sans',
};
